"""My first DB migrate

Revision ID: d5f7cd095469
Revises: 
Create Date: 2023-03-24 16:00:14.593209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f7cd095469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('Long_URL', sa.String(), nullable=True),
    sa.Column('Short_URL', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    # ### end Alembic commands ###
